### ISSUE TITLE
Storefront Deli Them Issues

### ISSUE THREAD

**Issue by mybizdw** [woocommerce/deli#23]
When I go to Deli Theme Customizing, then making my changes - the Save & Publish button is not working. When I click on the Save & Publish button it just goes back to the Save & Publish button, not to just Save. 
If I go to ext it out of the Customizing I receive a Popup saying - 
"Do you want to leave this sites?
  Changes you made may not be saved. "

**Comment by GlennMartin1** [comment]
I believe you may need to log out of WordPress and log back in. 

If you are in the Customizer for an extended period of inactivity without saving, eventually you will need to log out and log back in.

Try it.

**Comment by GlennMartin1** [comment]
I think (not sure) that this is a WordPress thing (not Storefront or Deli), and it may be affecting only specific browsers (I know it happens in Chrome).

**Comment by mybizdw** [comment]
GlennMartin1 I did as you suggested. Logged out back in no change. I cleared my cache no change. These were on Chrome. I then went to Internet Explorer tried to do Customize on there no change, the save button not working and saving the changed.

**Comment by jameskoster** [comment]
@mybizdw which versions of everything are you running? I just tested this locally using the latest versions of WordPress, Storefront and Deli and wasn't able to replicate the issue you describe.

**Comment by tiagonoronha** [comment]
@mybizdw I also tested and wasn't able to replicate the issue.

Please test Deli with any other plugins besides WooCommerce to make sure there isn't a conflict somewhere.
