### ISSUE TITLE
Comment text color is same as BG color.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/deli#36]
<img width="839" alt="screen shot 2018-11-05 at 10 56 52 am" src="https://user-images.githubusercontent.com/7317227/48009418-b1cffd80-e0e9-11e8-8040-23ede2fd2cde.png">
(Text highlighted with cursor in screenshot for readability)

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/deli/pull/40
