### ISSUE TITLE
[WP 5.0] Full-screen 5 and 6 columns going outside boundaries

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/deli#37]
<img width="1668" alt="screen shot 2018-11-05 at 2 29 38 pm" src="https://user-images.githubusercontent.com/7317227/48021753-5876c700-e107-11e8-8332-eb7340a6a95b.png">

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/deli/pull/39
