### ISSUE TITLE
[WP 5.0] Extra wide images go outside bounds when no sidebar is used

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/deli#38]
<img width="1530" alt="screen shot 2018-11-05 at 2 34 46 pm" src="https://user-images.githubusercontent.com/7317227/48022057-1b5f0480-e108-11e8-857b-f41fd8b388df.png">
<img width="1556" alt="screen shot 2018-11-05 at 2 35 00 pm" src="https://user-images.githubusercontent.com/7317227/48022058-1b5f0480-e108-11e8-96e6-0a7ecf998ed2.png">

**Comment by tiagonoronha** [comment]
Same as https://github.com/woocommerce/deli/issues/37
