### ISSUE TITLE
Block Editor: Can not see texts in the post content

### ISSUE THREAD

**Issue by htdat** [woocommerce/deli#44]
## Describe the bug

Block Editor: Can not see texts in the post content.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront + this child theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce

1. Create a post with Block editor.
2. Try adding some basic blocks like paragraph, heading, list, etc. 

## Screenshots

Back-end - issue here: 

![Screen Shot on 2020-05-26 at 14:46:16](https://user-images.githubusercontent.com/10045087/82874161-be33d980-9f5f-11ea-9076-354aaa3cfb80.png)

Front-end: 
![Screen Shot on 2020-05-26 at 14:46:34](https://user-images.githubusercontent.com/10045087/82874149-ba07bc00-9f5f-11ea-9ded-2efaba45a414.png)

## Expected behavior

I can see texts in the block editor without any issue. 

2998947-zen

**Comment by nielslange** [comment]
Hello @htdat 👋 Thanks for reporting this issue! I just fixed it in https://github.com/woocommerce/deli/pull/45, thus, feel free to test the fix. 😀
